### ISSUE TITLE
JsonSchema does not correspond to Serde representation

### ISSUE THREAD

**Issue by hgzimmerman** [krisprice/ipnet#40]
Currently, the `JsonSchema` trait is derived instead of manually implemented to match the parser for `IpNet`, `IpV4Net`, and `IpV6Net`.
This causes it to generate a schema object that indicates that for `IpV4Net`, the serde deserializer expects a JSON object like:
```json
{
    "addr": "0.0.0.0",
    "prefix_len": 0
}
```
when in reality, the deserializer expects, and serializer produces: 
```json
"0.0.0.0/0"
```

This can be resolved by implementing `JsonSchema` manually

**Comment by krisprice** [comment]
Hi @hgzimmerman - thanks. Yeah I figured this would be needed hence asking in the original PR #31 if the default output was actually satisfactory. Since @smklein was the original requestor for this with the use case at his employer Oxide I wonder if he could weigh in here on whether this change will work for him or not? CC @ralpha and @xfbs in case they have opinions too.

Thanks

**Comment by smklein** [comment]
That change works for us - the `0.0.0.0/0` format actually matches our [hand-rolled implementation](https://github.com/oxidecomputer/omicron/blob/52dfddb9f5c0fe4e73910b387ffd5cd3e1414a89/common/src/api/external/mod.rs#L982-L1019) more closely than the derived version!

**Comment by krisprice** [comment]
Thanks @hgzimmerman and @smklein I've merged and published these fixes.

**Comment by hgzimmerman** [comment]
Thanks!
